### ISSUE TITLE
yarn start: Usage Error: Workspace 'dm3-backend' not found

### ISSUE THREAD

**Issue by wighawag** [dm3-org/dm3#754]
To reproduce:

```bash
git clone git@github.com:dm3-org/dm3.git
cd dm3
yarn
yarn start
```

```
Usage Error: Workspace 'dm3-backend' not found. Did you mean any of the following:
  - @dm3-org/dm3-backend
  - @dm3-org/dm3-billboard-client
  - @dm3-org/dm3-billboard-widget
  - @dm3-org/dm3-cli
  - @dm3-org/dm3-integration-tests
  - @dm3-org/dm3-lib-billboard-client-api
  - @dm3-org/dm3-lib-crypto
  - @dm3-org/dm3-lib-delivery
  - @dm3-org/dm3-lib-delivery-api
  - @dm3-org/dm3-lib-messaging
  - @dm3-org/dm3-lib-offchain-resolver-api
  - @dm3-org/dm3-lib-profile
  - @dm3-org/dm3-lib-shared
  - @dm3-org/dm3-lib-storage
  - @dm3-org/dm3-messenger-demo
  - @dm3-org/dm3-messenger-web
  - @dm3-org/dm3-messenger-widget
  - @dm3-org/dm3-offchain-resolver
  - @dm3-org/dm3-toplevel-alias
  - dm3?

```

**Comment by wighawag** [comment]
it seems it should be `yarn workspace @dm3-org/dm3-backend start` and not `yarn workspace dm3-backend start` as it is now in the package.json file

But after that I get this error :

```
body-parser deprecated undefined extended: provide extended option dist/index.js:66:27
{"message":{"text":"[Server] listening","port":"8080","dir":"/home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist"},"level":"info"}
/home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/utils.js:166
            throw Error("Missing ".concat(keyName, " in env"));
                  ^

Error: Missing SIGNING_PUBLIC_KEY in env
    at readKey (/home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/utils.js:166:19)
    at readKeysFromEnv (/home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/utils.js:172:24)
    at /home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/index.js:89:63
    at step (/home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/index.js:33:23)
    at Object.next (/home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/index.js:14:53)
    at /home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/index.js:4:12)
    at /home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/index.js:75:23
    at Object.<anonymous> (/home/wighawag/dev/github.com/dm3-org/dm3/packages/backend/dist/index.js:116:7)

Node.js v18.18.2

```


Any doc on how to get started ?
