### ISSUE TITLE
dm3-messenger-widget is using nodejs module, making not compatible with modern web

### ISSUE THREAD

**Issue by wighawag** [dm3-org/dm3#788]
Similar to this issue :https://github.com/dm3-org/dm3/issues/786 (which is using dm3-react, which I believe is deprecated), dm3-messenger-widget is not compatibel with vite

It is importing nodejs globals in a web browser environemnt, while it might work in frameowkr that add extra compatibility layer, it does not work in modern framework like vite.

It would be better if dm3 lib stay lean and use only web standard

```
browser-external:buffer:9 Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:buffer:9
(anonymous) @ bn.js:56
node_modules/.pnpm/bn.js@5.2.1/node_modules/bn.js/lib/bn.js @ bn.js:3547
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@ethersproject+bignumber@5.7.0/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js @ bignumber.ts:11
__init @ chunk-ANIWD3T6.js?v=e5b7bde1:15
node_modules/.pnpm/@ethersproject+bignumber@5.7.0/node_modules/@ethersproject/bignumber/lib.esm/index.js @ index.ts:1
__init @ chunk-ANIWD3T6.js?v=e5b7bde1:15
node_modules/.pnpm/@ethersproject+abi@5.7.0/node_modules/@ethersproject/abi/lib.esm/fragments.js @ fragments.ts:3
__init @ chunk-ANIWD3T6.js?v=e5b7bde1:15
node_modules/.pnpm/@ethersproject+abi@5.7.0/node_modules/@ethersproject/abi/lib.esm/index.js @ index.ts:3
__init @ chunk-ANIWD3T6.js?v=e5b7bde1:15
node_modules/.pnpm/@ethersproject+contracts@5.7.0/node_modules/@ethersproject/contracts/lib.esm/index.js @ index.ts:3
__init @ chunk-ANIWD3T6.js?v=e5b7bde1:15
node_modules/.pnpm/ethers@5.7.2/node_modules/ethers/lib.esm/ethers.js @ ethers.ts:3
__init @ chunk-ANIWD3T6.js?v=e5b7bde1:15
node_modules/.pnpm/ethers@5.7.2/node_modules/ethers/lib.esm/index.js @ index.ts:5
__init @ chunk-ANIWD3T6.js?v=e5b7bde1:15
node_modules/.pnpm/@dm3-org+dm3-lib-crypto@1.0.6/node_modules/@dm3-org/dm3-lib-crypto/dist/Encryption.js @ Encryption.ts:1
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-crypto@1.0.6/node_modules/@dm3-org/dm3-lib-crypto/dist/index.js @ index.ts:1
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-profile@1.0.6/node_modules/@dm3-org/dm3-lib-profile/dist/Profile.js @ Profile.ts:1
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-profile@1.0.6/node_modules/@dm3-org/dm3-lib-profile/dist/index.js @ index.ts:2
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-storage@1.0.6/node_modules/@dm3-org/dm3-lib-storage/dist/location/Dm3Storage.js @ Dm3Storage.ts:3
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-storage@1.0.6/node_modules/@dm3-org/dm3-lib-storage/dist/index.js @ index.ts:1
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-messenger-widget@1.0.13_@babel+plugin-syntax-flow@7.23.3_@babel+plugin-transform_qfrqo3v6v4ma2mmrjxj4xp45ia/node_modules/@dm3-org/dm3-messenger-widget/dist/cjs/index.js @ index.js:7
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
(anonymous) @ index.js:21927
browser-external:stream:9 Module "stream" has been externalized for browser compatibility. Cannot access "stream.Transform" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
get @ browser-external:stream:9
node_modules/.pnpm/iconv-lite@0.6.3/node_modules/iconv-lite/lib/index.js @ index.js:168
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/whatwg-encoding@2.0.0/node_modules/whatwg-encoding/lib/whatwg-encoding.js @ whatwg-encoding.js:2
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-profile@1.0.6/node_modules/@dm3-org/dm3-lib-profile/dist/profileResolver/JsonResolver.js @ JsonResolver.ts:2
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-profile@1.0.6/node_modules/@dm3-org/dm3-lib-profile/dist/profileResolver/index.js @ index.ts:3
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-profile@1.0.6/node_modules/@dm3-org/dm3-lib-profile/dist/index.js @ index.ts:24
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-storage@1.0.6/node_modules/@dm3-org/dm3-lib-storage/dist/location/Dm3Storage.js @ Dm3Storage.ts:3
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-lib-storage@1.0.6/node_modules/@dm3-org/dm3-lib-storage/dist/index.js @ index.ts:1
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
node_modules/.pnpm/@dm3-org+dm3-messenger-widget@1.0.13_@babel+plugin-syntax-flow@7.23.3_@babel+plugin-transform_qfrqo3v6v4ma2mmrjxj4xp45ia/node_modules/@dm3-org/dm3-messenger-widget/dist/cjs/index.js @ index.js:7
__require2 @ chunk-ANIWD3T6.js?v=e5b7bde1:18
(anonymous) @ index.js:21927
auth-http.ts:11 Uncaught ReferenceError: process is not defined
    at node_modules/.pnpm/@dm3-org+dm3-lib-delivery-api@1.0.6/node_modules/@dm3-org/dm3-lib-delivery-api/dist/auth-http.js (auth-http.ts:11:27)
    at __require2 (chunk-ANIWD3T6.js?v=e5b7bde1:18:50)
    at node_modules/.pnpm/@dm3-org+dm3-lib-delivery-api@1.0.6/node_modules/@dm3-org/dm3-lib-delivery-api/dist/index.js (index.ts:1:1)
    at __require2 (chunk-ANIWD3T6.js?v=e5b7bde1:18:50)
    at node_modules/.pnpm/@dm3-org+dm3-messenger-widget@1.0.13_@babel+plugin-syntax-flow@7.23.3_@babel+plugin-transform_qfrqo3v6v4ma2mmrjxj4xp45ia/node_modules/@dm3-org/dm3-messenger-widget/dist/cjs/index.js (index.js:21:25)
    at __require2 (chunk-ANIWD3T6.js?v=e5b7bde1:18:50)
    at index.js:21927:15
```

Reproduction: https://github.com/bug-reproduction/vite-dm3-messenger-widget

```
git clone https://github.com/bug-reproduction/vite-dm3-messenger-widget
cd vite-dm3-react
pnpm i
pnpm dev
```

**Comment by steffenkux** [comment]
Thanks, we will check this.

**Comment by steffenkux** [comment]
@Bhupesh-mfsi please analyse
