### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by enghibrahem** [dm3-org/dm3#902]
when i run https://github.com/dm3-org/dm3/tree/develop/packages/messenger-widget ,it run fine and its functionality works fine, but after run project , i faced error message:
![image](https://github.com/dm3-org/dm3/assets/167298173/0506b8cf-f125-48b1-a437-e73e28a02720)
missing response (requestBody="{"data":"0xea9cd3bf000000000000000000000000f5b24cd05d6e6e9b8ac2b97cd90c38a8f2df57fb000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000001ff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000cb0000000000000000000000000000000000000000000000000000000000000020a37f8ac110b2c88c326e7d2848321a770f284548a466bcf8ce811ddc2e1bea8a","sender":"0x2bad1fec0a2629757470984284c11ea00adb8e6f"}", requestMethod="POST", serverError={}, url="https://dm3-test-worker.alex-941.workers.dev/", code=SERVER_ERROR, version=web/5.7.1)
at Logger.makeError (http://localhost:3000/static/js/bundle.js:40629:19)
at Logger.throwError (http://localhost:3000/static/js/bundle.js:40638:16)
at http://localhost:3000/static/js/bundle.js:51804:20
at Generator.throw ()
at rejected (http://localhost:3000/static/js/bundle.js:51574:32)

when i close it , it every thing work ,fine .
FYI:
I run project by using: Yarn start

node version is: v18.20.2

**Comment by enghibrahem** [comment]
i solved it by adding try catch 

![image_2024-04-18_11-02-50](https://github.com/dm3-org/dm3/assets/167298173/9da956d5-cb50-4033-ab5f-68623f48453f)
